version: '3.6'
services:
  function-builder:
    build:
      context: .
    ports:
      - '3000:3001'
    volumes:
      - .:/app/server
      - ../FunctionWatcher:/app/functionWatcher
      - /var/run/docker.sock:/var/run/docker.sock
